services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
       db:
         condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postreaddb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - D:/postread_images:/uploads
  db:
     image: postgres:latest
     container_name: postreadpostgres
     restart: always
     user: postgres
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postreaddb
       - POSTGRES_PASSWORD=${DB_PASSWORD}
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: postread_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postread.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
   db-data:
   pgadmin-data: