spring:
  application:
    name: postread
  datasource:
    url: jdbc:postgresql://db:5432/postreaddb
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        # Явно указываем использовать UTC для всех временных меток
        connection:
          timezone: UTC
    # Добавляем это свойство для корректной работы с временем
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: true

# Устанавливаем системный часовой пояс
app:
  upload:
    dir: /uploads
  timezone: Europe/Moscow

postread:
  secret: drfghjk324567klfg
  expirationMs: 60000